# Generated by Django 3.1.7 on 2021-03-11 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=255)),
                ('picture_path', models.ImageField(upload_to='')),
                ('status', models.CharField(choices=[('AV', 'Available'), ('OH', 'On hold'), ('MS', 'Missing'), ('IS', 'In storage')], max_length=255)),
                ('registered_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField(choices=[(1, 'Row 1'), (2, 'Row 2'), (3, 'Row 3')])),
                ('col', models.IntegerField(choices=[(1, 'Column 1'), (2, 'Column 2'), (3, 'Column 3')])),
                ('shelf_status', models.BooleanField(default=False)),
                ('current_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iotlib.book')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalBook',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=255)),
                ('picture_path', models.TextField(max_length=100)),
                ('status', models.CharField(choices=[('AV', 'Available'), ('OH', 'On hold'), ('MS', 'Missing'), ('IS', 'In storage')], max_length=255)),
                ('registered_date', models.DateTimeField(blank=True, editable=False)),
                ('modified_date', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical book',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
